ALTER TABLE users MODIFY COLUMN password_hash VARCHAR(255) NULL;
ALTER TABLE users ADD COLUMN google_id VARCHAR(255) NULL UNIQUE AFTER email;
ALTER TABLE users ADD COLUMN profile_picture VARCHAR(500) NULL AFTER auth_provider;
